### ISSUE TITLE
Processing time

### ISSUE THREAD

**Issue by casiatao** [franktpmvu/NeighborTrack#2]
Does post-processing take a long time and is it hardware-friendly?

**Comment by franktpmvu** [comment]
It depends on how often you experience occlusion, if all of video without occlude, inference speed will equal to original method.

Based on my experience, VOT dataset will decrease 33% inference speed (means 0.66 x original fps).
each neighbor need reverse track n frame. 

For now, each neighbor use only one for loop to get reverse tracklet. If your SOT method support multiple kernel, you can speed up this for loop:
https://github.com/franktpmvu/NeighborTrack/blob/89aa0781c5b59ac570e3c1c47cca5b1dd6a5f945/neighbortrack.py#L150
it will be helpful.
