### ISSUE TITLE
working on Real Time (Question)

### ISSUE THREAD

**Issue by arielkantorovich** [franktpmvu/NeighborTrack#6]
Hi,
I read the paper nice idea. My question is if the algorithm can run on real-time applications my intuition said no but still I want to ask if you try to run this algorithm in real-time on GPU.

**Comment by franktpmvu** [comment]
Actually it depends on your basic algorithm.
My method is just a post-processing method.
For example, in case of OSTrack this model reduces fps from 3.63 to 43% of OSTrack to 1.58 FPS but if you have a fast model like 100+fps then my post processing method would be the realtime method.

hope this can answers your question.


more information can be found below
https://github.com/franktpmvu/NeighborTrack/issues/2#issuecomment-1342055070
