### ISSUE TITLE
如何判断目标被遮挡？

### ISSUE THREAD

**Issue by ElliottZhen** [franktpmvu/NeighborTrack#9]
您好，很棒的工作。想请教您一些问题。
请问跟踪器是在任何情况都使用文中的后处理操作吗？如果不是，那么如何判断目标什么时候被遮挡？
非常期待您的回复，祝您科研顺利，身体健康！

**Comment by ElliottZhen** [comment]
@franktpmvu

**Comment by ElliottZhen** [comment]
不好意思，我仔细阅读了论文后边，找到了

**Comment by franktpmvu** [comment]
In Figure 2.  As you can see, if the backward tracking and forward tracking mismatch, it might have some occlusion, see the end of section 4.1 in the paper. the threshold is 0.4 
in code: https://github.com/franktpmvu/NeighborTrack/blob/29c6267c36a0407bbe7bf3bf3fd98763b7eb1103/neighbortrack.py#L29C9-L29C28

![image](https://github.com/franktpmvu/NeighborTrack/assets/38975575/0a91ec5e-71c0-4e32-8be6-2623dbaa682c)
